openapi: 3.0.0
info:
  title: Video Sentiment Analysis API
  version: 1.0.0
paths:
  /analyze:
    post:
      summary: Analyze a TikTok video
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  format: uri
                  description: The URL of the TikTok video to analyze.
                content_analysis:
                  type: boolean
                  description: Whether to perform content analysis on the video.
                  default: true
      responses:
        '200':
          description: Analysis successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalysisReport'
        '400':
          description: Invalid input

components:
  schemas:
    Video:
      type: object
      properties:
        url:
          type: string
          format: uri
        content_summary:
          type: string
        derived_sentiment:
          type: string

    Comment:
      type: object
      properties:
        id:
          type: string
        text:
          type: string
        analyzed_sentiment:
          type: string

    AnalysisReport:
      type: object
      properties:
        video:
          $ref: '#/components/schemas/Video'
        comments:
          type: array
          items:
            $ref: '#/components/schemas/Comment'
        sentiment_statistics:
          type: object
          properties:
            positive:
              type: number
              format: float
            negative:
              type: number
              format: float
            neutral:
              type: number
              format: float
        keyword_cloud:
          type: array
          items:
            type: object
            properties:
              text:
                type: string
              value:
                type: integer
        conclusion:
          type: string
        warnings:
          type: array
          items:
            type: string
